# Generated by Django 5.0.7 on 2024-07-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0002_animal_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='idade_aproximada',
            field=models.IntegerField(null=True),
        ),
    ]
